// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  clinicDocs: create.doc("clinicDocs", {"en/index.mdx": () => import("../src/content/docs/clinic/en/index.mdx?collection=clinicDocs"), "en/team/experts.mdx": () => import("../src/content/docs/clinic/en/team/experts.mdx?collection=clinicDocs"), "en/team/invitations.mdx": () => import("../src/content/docs/clinic/en/team/invitations.mdx?collection=clinicDocs"), "en/analytics/dashboard.mdx": () => import("../src/content/docs/clinic/en/analytics/dashboard.mdx?collection=clinicDocs"), "en/pricing/plans.mdx": () => import("../src/content/docs/clinic/en/pricing/plans.mdx?collection=clinicDocs"), "en/pricing/revenue.mdx": () => import("../src/content/docs/clinic/en/pricing/revenue.mdx?collection=clinicDocs"), "en/getting-started/branding.mdx": () => import("../src/content/docs/clinic/en/getting-started/branding.mdx?collection=clinicDocs"), "en/getting-started/setup.mdx": () => import("../src/content/docs/clinic/en/getting-started/setup.mdx?collection=clinicDocs"), }),
  developerDocs: create.doc("developerDocs", {"en/index.mdx": () => import("../src/content/docs/developer/en/index.mdx?collection=developerDocs"), "en/api/endpoints.mdx": () => import("../src/content/docs/developer/en/api/endpoints.mdx?collection=developerDocs"), "en/api/authentication.mdx": () => import("../src/content/docs/developer/en/api/authentication.mdx?collection=developerDocs"), "en/api/errors.mdx": () => import("../src/content/docs/developer/en/api/errors.mdx?collection=developerDocs"), "en/integrations/stripe.mdx": () => import("../src/content/docs/developer/en/integrations/stripe.mdx?collection=developerDocs"), "en/integrations/calendar.mdx": () => import("../src/content/docs/developer/en/integrations/calendar.mdx?collection=developerDocs"), "en/webhooks/events.mdx": () => import("../src/content/docs/developer/en/webhooks/events.mdx?collection=developerDocs"), "en/webhooks/overview.mdx": () => import("../src/content/docs/developer/en/webhooks/overview.mdx?collection=developerDocs"), }),
  expertDocs: create.doc("expertDocs", {"en/index.mdx": () => import("../src/content/docs/expert/en/index.mdx?collection=expertDocs"), "en/earnings/pricing.mdx": () => import("../src/content/docs/expert/en/earnings/pricing.mdx?collection=expertDocs"), "en/earnings/payouts.mdx": () => import("../src/content/docs/expert/en/earnings/payouts.mdx?collection=expertDocs"), "en/getting-started/services.mdx": () => import("../src/content/docs/expert/en/getting-started/services.mdx?collection=expertDocs"), "en/getting-started/availability.mdx": () => import("../src/content/docs/expert/en/getting-started/availability.mdx?collection=expertDocs"), "en/getting-started/profile.mdx": () => import("../src/content/docs/expert/en/getting-started/profile.mdx?collection=expertDocs"), "en/top-expert/requirements.mdx": () => import("../src/content/docs/expert/en/top-expert/requirements.mdx?collection=expertDocs"), "en/top-expert/benefits.mdx": () => import("../src/content/docs/expert/en/top-expert/benefits.mdx?collection=expertDocs"), }),
  legal: create.doc("legal", {}),
  marketing: create.doc("marketing", {}),
  patientDocs: create.doc("patientDocs", {"en/index.mdx": () => import("../src/content/docs/patient/en/index.mdx?collection=patientDocs"), "en/booking.mdx": () => import("../src/content/docs/patient/en/booking.mdx?collection=patientDocs"), "en/faq.mdx": () => import("../src/content/docs/patient/en/faq.mdx?collection=patientDocs"), "en/reviews.mdx": () => import("../src/content/docs/patient/en/reviews.mdx?collection=patientDocs"), "en/payments.mdx": () => import("../src/content/docs/patient/en/payments.mdx?collection=patientDocs"), }),
  trust: create.doc("trust", {}),
};
export default browserCollections;