// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  expert: create.doc("expert", {"pt/index.mdx": () => import("../src/content/help/expert/pt/index.mdx?collection=expert"), "en/index.mdx": () => import("../src/content/help/expert/en/index.mdx?collection=expert"), "pt/top-expert/requirements.mdx": () => import("../src/content/help/expert/pt/top-expert/requirements.mdx?collection=expert"), "pt/top-expert/benefits.mdx": () => import("../src/content/help/expert/pt/top-expert/benefits.mdx?collection=expert"), "pt/earnings/pricing.mdx": () => import("../src/content/help/expert/pt/earnings/pricing.mdx?collection=expert"), "pt/earnings/payouts.mdx": () => import("../src/content/help/expert/pt/earnings/payouts.mdx?collection=expert"), "pt/getting-started/services.mdx": () => import("../src/content/help/expert/pt/getting-started/services.mdx?collection=expert"), "pt/getting-started/availability.mdx": () => import("../src/content/help/expert/pt/getting-started/availability.mdx?collection=expert"), "pt/getting-started/profile.mdx": () => import("../src/content/help/expert/pt/getting-started/profile.mdx?collection=expert"), "en/top-expert/requirements.mdx": () => import("../src/content/help/expert/en/top-expert/requirements.mdx?collection=expert"), "en/top-expert/benefits.mdx": () => import("../src/content/help/expert/en/top-expert/benefits.mdx?collection=expert"), "en/getting-started/services.mdx": () => import("../src/content/help/expert/en/getting-started/services.mdx?collection=expert"), "en/getting-started/availability.mdx": () => import("../src/content/help/expert/en/getting-started/availability.mdx?collection=expert"), "en/getting-started/profile.mdx": () => import("../src/content/help/expert/en/getting-started/profile.mdx?collection=expert"), "en/earnings/pricing.mdx": () => import("../src/content/help/expert/en/earnings/pricing.mdx?collection=expert"), "en/earnings/payouts.mdx": () => import("../src/content/help/expert/en/earnings/payouts.mdx?collection=expert"), }),
  patient: create.doc("patient", {"en/index.mdx": () => import("../src/content/help/patient/en/index.mdx?collection=patient"), "en/booking.mdx": () => import("../src/content/help/patient/en/booking.mdx?collection=patient"), "en/faq.mdx": () => import("../src/content/help/patient/en/faq.mdx?collection=patient"), "en/reviews.mdx": () => import("../src/content/help/patient/en/reviews.mdx?collection=patient"), "en/payments.mdx": () => import("../src/content/help/patient/en/payments.mdx?collection=patient"), "pt/index.mdx": () => import("../src/content/help/patient/pt/index.mdx?collection=patient"), "pt/booking.mdx": () => import("../src/content/help/patient/pt/booking.mdx?collection=patient"), "pt/faq.mdx": () => import("../src/content/help/patient/pt/faq.mdx?collection=patient"), "pt/reviews.mdx": () => import("../src/content/help/patient/pt/reviews.mdx?collection=patient"), "pt/payments.mdx": () => import("../src/content/help/patient/pt/payments.mdx?collection=patient"), }),
  workspace: create.doc("workspace", {"en/index.mdx": () => import("../src/content/help/workspace/en/index.mdx?collection=workspace"), "en/team/experts.mdx": () => import("../src/content/help/workspace/en/team/experts.mdx?collection=workspace"), "en/team/invitations.mdx": () => import("../src/content/help/workspace/en/team/invitations.mdx?collection=workspace"), "en/getting-started/branding.mdx": () => import("../src/content/help/workspace/en/getting-started/branding.mdx?collection=workspace"), "en/getting-started/setup.mdx": () => import("../src/content/help/workspace/en/getting-started/setup.mdx?collection=workspace"), "en/pricing/plans.mdx": () => import("../src/content/help/workspace/en/pricing/plans.mdx?collection=workspace"), "en/pricing/revenue.mdx": () => import("../src/content/help/workspace/en/pricing/revenue.mdx?collection=workspace"), "en/analytics/dashboard.mdx": () => import("../src/content/help/workspace/en/analytics/dashboard.mdx?collection=workspace"), }),
};
export default browserCollections;