import { docsOptions } from '@/lib/layout.shared';
import { getPortalSource, isValidPortal, type PortalKey } from '@/lib/source';
import type { FumadocsLanguage } from '@/lib/fumadocs-i18n.config';
import { DocsLayout } from 'fumadocs-ui/layouts/docs';
import { notFound } from 'next/navigation';
import type { ReactNode } from 'react';

/**
 * Portal Help Center Layout
 *
 * Provides DocsLayout with sidebar for each help portal (patient, expert, workspace).
 * Locale comes from URL params via [locale] segment.
 *
 * URL Structure:
 * - /help/patient (locale = 'en')
 * - /pt/help/patient (locale = 'pt')
 *
 * @see https://fumadocs.vercel.app/docs/ui/layouts/docs
 */

interface LayoutProps {
  children: ReactNode;
  params: Promise<{ locale: string; portal: string }>;
}

/**
 * Map next-intl locale to Fumadocs language
 */
function mapToFumadocsLocale(locale: string): FumadocsLanguage {
  if (locale === 'pt-BR' || locale === 'pt') return 'pt';
  if (locale === 'es') return 'en';
  return 'en';
}

export default async function PortalDocsLayout({ children, params }: LayoutProps) {
  const { locale, portal } = await params;

  if (!isValidPortal(portal)) {
    notFound();
  }

  const fumadocsLocale = mapToFumadocsLocale(locale);
  const source = getPortalSource(portal);
  const tree = source.pageTree[fumadocsLocale] ?? source.pageTree.en;

  return (
    <DocsLayout tree={tree} {...docsOptions(fumadocsLocale)}>
      {children}
    </DocsLayout>
  );
}

/**
 * Generate static params for all portals
 * Note: locale params are generated by parent [locale] layout
 */
export function generateStaticParams() {
  const portals: PortalKey[] = ['patient', 'expert', 'workspace'];
  return portals.map((portal) => ({ portal }));
}

