import { docsOptions } from '@/lib/layout.shared';
import { getPortalSource, isValidPortal, type PortalKey } from '@/lib/source';
import type { FumadocsLanguage } from '@/lib/fumadocs-i18n.config';
import { DocsLayout } from 'fumadocs-ui/layouts/docs';
import { notFound } from 'next/navigation';
import type { ReactNode } from 'react';

/**
 * Portal Help Center Layout
 *
 * Provides DocsLayout with sidebar for each help portal (patient, expert, workspace).
 * Locale comes from URL params via [locale] segment.
 *
 * URL Structure:
 * - /help/patient (locale = 'en')
 * - /pt/help/patient (locale = 'pt')
 *
 * @see https://fumadocs.vercel.app/docs/ui/layouts/docs
 *
 * @example
 * ```tsx
 * // Used by Next.js App Router - wraps portal documentation pages
 * // URL: /help/patient or /pt/help/patient
 * <Layout params={Promise.resolve({ locale: 'en', portal: 'patient' })}>
 *   <PortalDocsPage />
 * </Layout>
 * ```
 */

interface LayoutProps {
  children: ReactNode;
  params: Promise<{ locale: string; portal: string }>;
}

/**
 * Map next-intl locale to Fumadocs language.
 *
 * Note: 'es' (Spanish) intentionally falls back to 'en' because Spanish
 * documentation is not yet available. TODO: Add Spanish docs and update mapping.
 */
function mapToFumadocsLocale(locale: string): FumadocsLanguage {
  if (locale === 'pt-BR' || locale === 'pt') return 'pt';
  // Spanish falls back to English - Spanish docs not yet available
  if (locale === 'es') return 'en';
  return 'en';
}

export default async function PortalDocsLayout({ children, params }: LayoutProps) {
  const { locale, portal } = await params;

  if (!isValidPortal(portal)) {
    notFound();
  }

  const fumadocsLocale = mapToFumadocsLocale(locale);
  const source = getPortalSource(portal);
  const tree = source.pageTree[fumadocsLocale] ?? source.pageTree.en;

  return (
    <DocsLayout tree={tree} {...docsOptions(fumadocsLocale)}>
      {children}
    </DocsLayout>
  );
}

/**
 * Generate static params for all portals.
 * Note: locale params are generated by parent [locale] layout.
 *
 * @returns Array of portal parameters
 *
 * @example
 * ```tsx
 * // Returns:
 * // [{ portal: 'patient' }, { portal: 'expert' }, { portal: 'workspace' }]
 * ```
 */
export function generateStaticParams(): Array<{ portal: PortalKey }> {
  const portals: PortalKey[] = ['patient', 'expert', 'workspace'];
  return portals.map((portal) => ({ portal }));
}

